let data = [
    {
        id: '', // auto genterated
        title: "", // Event title
        category: "", // Event // Scholarship // Internship
        organization: "", // organization / organizor
        description: "", // description of the event
        deadline: "", // last date to apply/register
        location: "", // location of the targeted event 
        time: "", // when will the event starts/happens 
        fee: "", // entry/regestraion fee
        payment: "", // salary / will you receive any money from the organization?
        imagePath: '', // image linl or path > currently unused
        link: '', // website or event related link
    },
    {
        id: '1774409093989',
        title: "Merit-Based Excellence Scholarship",
        category: "Scholarship",
        organization: "National Education Foundation",
        description: "Full tuition coverage for outstanding students demonstrating academic excellence and leadership potential.",
        deadline: "2026/04/15",
        location: "Nationwide",
        time: "",       
        fee: "Free",
        payment: "",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409109433',
        title: "STEM Women Empowerment Grant",
        category: "Scholarship",
        organization: "Tech Diversity Initiative",
        description: "Supporting women pursuing careers in science, technology, engineering, and mathematics fields.",
        deadline: "2026/05/01",
        location: "USA",
        time: "",
        fee: "Free",
        payment: "$10,000",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409132008',
        title: "Community Service Leadership Award",
        category: "Scholarship",
        organization: "Civic Engagement Foundation",
        description: "Recognizing students who have made significant contributions to their communities through volunteer work.",
        deadline: "2026/03/30",
        location: "Local",
        time: "",
        fee: "$15",
        payment: "$5,000",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409142380',
        title: "International Education Scholarship",
        category: "Scholarship",
        organization: "Global Learning Foundation",
        description: "Supporting students who wish to study abroad and gain international cultural experience.",
        deadline: "2026/04/30",
        location: "International",
        time: "",
        fee: "$25",
        payment: "$8,000",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409160783',
        title: "First-Generation Scholar Award",
        category: "Scholarship",
        organization: "Higher Education Access Initiative",
        description: "Dedicated to supporting first-generation college students pursuing higher education.",
        deadline: "2026/05/15",
        location: "National",
        time: "",
        fee: "Free",
        payment: "$7,500",
        imagePath: '',
        link: '',
    },  
    {
        id: '1774409170742',
        title: "Software Engineering Intern",
        category: "Internship",
        organization: "TechCorp Solutions",
        description: "Join our engineering team to work on cutting-edge web applications and gain hands-on experience with modern tech stack.",
        deadline: "2026/04/20",
        location: "Remote",
        time: "3 months",
        fee: "",
        payment: "$25/hour",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409179577',
        title: "Marketing & Social Media Intern",
        category: "Internship",
        organization: "Creative Agency Plus",
        description: "Help create engaging content and manage social media campaigns for exciting brands and startups.",
        deadline: "2026/04/10",
        location: "Hybrid",
        time: "6 months",
        fee: "",
        payment: "$20/hour",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409190234',
        title: "Data Science Research Intern",
        category: "Internship",
        organization: "AI Research Lab",
        description: "Work alongside PhD researchers on machine learning projects and contribute to published research papers.",
        deadline: "2026/03/25",
        location: "On-Site",
        time: "4 months",
        fee: "",
        payment: "$30/hour",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409200123',
        title: "UX/UI Design Intern",
        category: "Internship",
        organization: "Digital Design Studios",
        description: "Create user-centered designs for web and mobile applications while learning industry best practices.",
        deadline: "2026/04/05",
        location: "Remote",
        time: "3 months",
        fee: "",
        payment: "$22/hour",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409210456',
        title: "Business Operations Intern",
        category: "Internship",
        organization: "Corporate Solutions Inc",
        description: "Support business operations and gain insight into management, finance, and strategic planning.",
        deadline: "2026/04/15",
        location: "Hybrid",
        time: "5 months",
        fee: "",
        payment: "$18/hour",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409220789',
        title: "Tech Career Fair 2026",
        category: "Event",
        organization: "University Career Center",
        description: "Meet recruiters from top tech companies, attend workshops, and network with industry professionals.",
        deadline: "2026/03/10",
        location: "Campus Center",
        time: "2026/03/15",
        fee: "Free",
        payment: "",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409230123',
        title: "Startup Pitch Competition",
        category: "Event",
        organization: "Entrepreneurship Club",
        description: "Pitch your startup idea to investors and compete for $10,000 in seed funding and mentorship.",
        deadline: "2026/03/20",
        location: "Innovation Hub",
        time: "2026/04/05",
        fee: "$50",
        payment: "$10K Prize",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409250789',
        title: "Industry Panel Discussion: Future of AI",
        category: "Event",
        organization: "Computer Science Department",
        description: "Hear from leading AI researchers and engineers about the future of artificial intelligence and career opportunities.",
        deadline: "2026/03/28",
        location: "Main Auditorium",
        time: "2026/04/08",
        fee: "Free",
        payment: "Free",
        imagePath: '',
        link: '',
    },
    {
        id: '1774409260123',
        title: "Career Development Summit",
        category: "Event",
        organization: "Student Services",
        description: "A full-day event featuring keynote speakers, workshop sessions, and one-on-one mentoring opportunities.",
        deadline: "2026/04/01",
        location: "Convention Center",
        time: "2026/04/22",
        fee: "$75",
        payment: "Free",
        imagePath: '',
        link: '',
    }
]